
version: '3.9'

services:

  data:

    image: postgres:15.2-alpine
    container_name: 'todos-data'

    restart: unless-stopped

    env_file: ./.env
    ports:
      - $PGSQL_LOCAL_PORT:$PGSQL_DOCKER_PORT

    environment:
      - POSTGRES_USER=$PGSQL_USER
      - POSTGRES_PASSWORD=$PGSQL_PASSWORD
      - POSTGRES_DB=$PGSQL_DB

    volumes:
      - db:/var/lib/postgresql

  app:

    depends_on:
      - data

    build: ./todos-app

    image: 'todos-app:reactive-axios'
    container_name: 'todos-app'

    restart: on-failure

    env_file: ./.env
    ports:
      - $SPRING_LOCAL_PORT:$SPRING_DOCKER_PORT

    environment:
      SPRING_APPLICATION_JSON: '{
            "spring.r2dbc.url"  : "r2dbc:postgresql://data:$PGSQL_DOCKER_PORT/$PGSQL_DB",
            "spring.r2dbc.username" : "$PGSQL_USER",
            "spring.r2dbc.password" : "$PGSQL_PASSWORD",
            "spring.jpa.hibernate.ddl-auto" : "update"
          }'

    stdin_open: true
    tty: true

  proxy:

    depends_on:
      - app

    image: nginx:1.24-alpine
    container_name: 'todos-proxy'

    restart: always

    env_file: ./.env
    ports:
      - $NGINX_LOCAL_PORT:$NGINX_DOCKER_PORT

    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro

volumes:
  db:
